### ISSUE TITLE
File.getBuffer()  error in new version 1.0.5

### ISSUE THREAD

**Issue by bva999** [pnp/pnpjs#103]
**### Category**
- [ ] Enhancement
- [ x] Bug
- [ ] Question
- [ ] Documentation gap/issue

**### Version** 

Please specify what version of the library you are using: [  1.0.5 ]

After the upgrade to version 1.0.5, the following code stopped working.

```
sp.web.getFolderByServerRelativeUrl(this.props.projectReferencesTemplatesLibraryUrl)
      .files.getByName(option.text + ".docx").getBuffer().then((buffer : ArrayBuffer) => {
        this.content = buffer;
      });
```

**Error:** 
Uncaught (in promise) TypeError: r.buffer is not a function
    at BufferParser.parseImpl (pipeline.ts:27)
    at parsers.ts:36
    at new Promise (<anonymous>)
    at BufferParser.ODataParserBase.parse (parsers.ts:35)
    at pipeline.ts:226

**Comment by patrick-rodgers** [comment]
Thanks, I see what happened. Sorry about that - will get a fix in.

**Comment by ahsanranjha** [comment]
Error in making file request using server relative path. The request path is invalid. It is adding api after pages library instead of site

pnp.sp.web.getFileByServerRelativeUrl("https://xxxxxx/Plus/DocumentLibrary/folder1/folder2/file.pdf").getBuffer().then((buffer : ArrayBuffer) => {
        this.content = buffer;
      });

https://xxxxxx/**Pages/gfs/**_api/web/getFileByServerRelativeUrl('/DocumentLibrary/folder1/folder2/file.pdf"')/$value

**Comment by patrick-rodgers** [comment]
Hi @ahsanranjha - this is a separate issue and shouldn't be tacked to the end of an existing thread. You haven't really provided enough details here to help, but my guess is that you need to provide the context within your SPFx webpart. Please see [getting started page](https://pnp.github.io/pnpjs/getting-started.html).

**Comment by patrick-rodgers** [comment]
Fixed, not yet merged. Will close issue on merge. Thanks!

**Comment by patrick-rodgers** [comment]
Fixed in 1.1.0

**Comment by pabmardo** [comment]
I have update to 1.1.0 the pnp/sp and the pnp/common and still facing the same issue
![image](https://user-images.githubusercontent.com/29203116/40663435-f25462ba-6358-11e8-93ad-6cdb5cd17af5.png)
![image](https://user-images.githubusercontent.com/29203116/40663495-1394b024-6359-11e8-99a2-a00087d3348e.png)

I'm importing properly, setting context at init time and reading the item properties works, only fails the getBuffer(), my call:
sp.web.getFileByServerRelativeUrl("/sites/SiteDEV/Shared Documents/tag-example.docx").getBuffer().
                 then((buffer: ArrayBuffer) => {
                   Dialog.alert("Finally!");
                 });

any tip? am I doing anything wrong?

**Comment by pabmardo** [comment]
Perfect! I've tested and its working as it should.... Then probably it was working as you suggested, with 1.0.4 but I downgraded the pnp/sp only and it failed for me too.... I ended doing the rest request.   As the documentation is very little, it would help being more specific, but amazing job people!!
Kudos
Pablo
