### ISSUE TITLE
SharePoint webpart seemingly losing context after a certain amount of time

### ISSUE THREAD

**Issue by cardinalpipkin** [pnp/pnpjs#2242]
I've moved this from the samples forum as it is an issue with sp pnp.

Situation/Environment - I have an SPFX built webpart that uses:

- SharePoint Online
- sp/pnp v3.1.0
- sp/pnp spfx-controls-react v3.5.0
- rush-stack-compiler-4.2 v0.1.1
- The webpart is a form which allows a user to add/update to a SharePoint list item(s).

Problem: The webpart loads fine. After about 5 minutes of inactivity on the form when a user tries to update their form (Save and Close button) it shows:

```
Error: Error making HttpClient request in queryable [401] Unauthorized ::> 
POST https://mySite/items(103) 401 (Unauthorized)
```

We believe it might be the webpart losing context after a certain period of time and a token is not being renewed. This is a theory.

Points to note:

- The form can add/update successfully before this approximate (around 5 mins) amount of time.
- When the issue occurs the form is responsive and all the controls can be interacted with, but any request to SharePoint throws the error above.
- We have developed an SPO webpart using V2 sp/pnp and have not experienced the same issue.
- The error occurs when the webpart is deployed to single page on SPO
- All SPO permissions are correct and checked
- There is one workflow that changes permissions when an item is modified but we have disabled this and checked and the error still occurs
- This error occurs in SP workbench also
- We noticed in the network tab in Edge that the x-Request-digest shows that something has expired early but we are unsure that this is the cause.
- We have studied the [documentation ](https://pnp.github.io/pnpjs/getting-started/#establish-context-within-an-spfx-service)closely

We are establishing context like this:

We have a helper/utils file which provides this:

```
import { SPFI, spfi, SPFx } from "@pnp/sp";

let sp: SPFI;
export const SetContext = (context) => {
    sp = spfi().using(SPFx(context));
};
```
In the parent component (not the root .ts file) we use:

```
React.useEffect(() => {
    Utils.SetContext(props.context);
    _getListItemsFromSP();
    getRoles();
  }, [
    currentUserLoginName,
    currentUserID
  ]);

  React.useEffect(() => {
    Utils.SetContext(props.context);
  }, [
  ]);
```
Previously we didn't use 2 useEffects, this is a failed attempt to make the context update more than once.

I hope that this is posted in the correct forum? And I don't believe it's a bug, but possibly the way we are establishing context with the new sp/pnp v3?

**Comment by patrick-rodgers** [comment]
Can you have a look at [this issue](https://github.com/pnp/pnpjs/issues/2186) which was fixed in 3.2. It seems like it might be the same - let us know if that works. Thanks!

**Comment by cardinalpipkin** [comment]
> Can you have a look at [this issue](https://github.com/pnp/pnpjs/issues/2186) which was fixed in 3.2. It seems like it might be the same - let us know if that works. Thanks!

Hi - that's made no difference unfortunately. I've updated to:

 "dependencies": {
    "@fluentui/react": "^8.61.1",
    "@microsoft/rush-stack-compiler-4.2": "^0.1.1",
    "@microsoft/sp-core-library": "1.13.1",
    "@microsoft/sp-lodash-subset": "1.13.1",
    "@microsoft/sp-office-ui-fabric-core": "1.13.1",
    "@microsoft/sp-property-pane": "1.13.1",
    "@microsoft/sp-webpart-base": "1.13.1",
    "@pnp/sp": "^3.2.0",
    "@pnp/spfx-controls-react": "^3.7.2",
    "lodash": "^4.17.21",
    "office-ui-fabric-react": "^7.174.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-icons": "^4.3.1",
    "react-quill": "^1.3.5",
    "use-state-with-callback": "^2.0.3"
  },
  "devDependencies": {
    "@types/react": "16.9.51",
    "@types/react-dom": "16.9.8",
    "@microsoft/sp-build-web": "1.13.1",
    "@microsoft/sp-tslint-rules": "1.13.1",
    "@microsoft/sp-module-interfaces": "1.13.1",
    "@microsoft/rush-stack-compiler-3.9": "0.4.47",
    "gulp": "~4.0.2",
    "ajv": "~5.2.2",
    "@types/webpack-env": "1.13.1"

But as mentioned no change to the problem.

**Comment by kofrimpong** [comment]
@patrick-rodgers Wanted you to know that this [issue](https://github.com/pnp/pnpjs/issues/2186) was not fixed in v3.2.0. I am still experiencing the error. It is locked so couldn't comment there.

**Comment by patrick-rodgers** [comment]
For everyone in this thread reporting an issue, **please create a repo we can clone that clearly shows the issue** you believe you have with the library. Please ensure that there are comments or sufficient information for us to understand what you believe to be wrong. As best I can tell the request digest caching issue is fixed. Please provide additional details beyond "it's not fixed" for us to investigate.

If you are using React + hooks and not using the page lifecycle methods such as onInit, it is very possible the context you think you are referencing is no longer valid due to page navigation happening on the client side. You'll need to step through your code to ensure that the context you are referencing is the one you think you are referencing.

**Comment by bcameron1231** [comment]
Agreed with @patrick-rodgers , if you could create a repository with the source code that would be helpful. It's unclear how the created sp context in your Utils class is actually being used based on the code that you have provided. 

Additionally, I would definitely make some modifications to your codebase that you've provided. The first being, that you should remove the additional set contexts, and I would either put in it in the init of the WebPart, or I would only do it in the empty dependency array effect you have. 

A side note, you shouldn't reference your props in your first effect without making sure it's a dependency of that effect. That's an improper use of hooks.

----------------------------------

Lastly, I've created my own solution using hooks and PnpJs v3.2.0 and I cannot reproduce the issues you are seeing. I waited 5 minutes, and 10 minutes and it worked every time. I suspect there is an issue with how your code is structured.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered.  Thank you @bcameron1231 for your excellent additional insight. As @patrick-rodgers mentioned, if you have further issues, please feel free to create a new issue and reference this one.

**Comment by bcameron1231** [comment]
If this issue pops up again, feel free to tag me in it, since I already have a functional component solution set up, it will make it easier to debug next time we get sample source available.

**Comment by cardinalpipkin** [comment]
Thanks Beau. Apologies for the late reply. We have this fixed now. We were probably setting context wrong as suggested, but SPBrowser was the fix that worked. But we will look into your recommendations.
Thank you.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
