### ISSUE TITLE
Can't use PnPJS 2.0 targeting SPFx 1.4.1 (SPO and SharePoint 2019)

### ISSUE THREAD

**Issue by sebastienlevert** [pnp/pnpjs#978]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.0]

Please specify what version(s) of SharePoint you are targeting: [2019, SPO]

### Expected / Desired Behavior / Question
I should be able to use SPFx 1.4.1 "at least" as the foundation for my solution as it could run on both SP2019 and SharePoint Online

### Observed Behavior
When using SPFx 1.4.1 as our foundation for a solution to ensure it works on both Online and SP2019, it's impossible to initialize PnPJS as it requires the `aadTokenProviderFactory` object as part of the context, which is not the case for SPFx 1.4.1 for Web Parts and Extensions.

### Steps to Reproduce
Just create a new solution targeting SP2019 and add PnPJS to the solution, you'll quickly see the red squigglies appear in VS Code.

![image](https://user-images.githubusercontent.com/7620955/71562868-9f82f280-2a54-11ea-9b2d-3de8ef57cf6e.png)

**Comment by sebastienlevert** [comment]
To add to the previous issue, even when using the `Web` object as a way to bypass this (and this seems indeed like a great idea!), we're getting some issues at compile time regarding Typescript errors.

```
[17:28:16] Error - typescript - node_modules\@pnp\sp\lists\types.d.ts(46,28): error TS1110: Type expected.
[17:28:16] Error - typescript - node_modules\@pnp\sp\lists\types.d.ts(46,88): error TS1005: '(' expected.
[17:28:16] Error - typescript - node_modules\@pnp\sp\lists\types.d.ts(136,27): error TS1110: Type expected.
[17:28:16] Error - typescript - node_modules\@pnp\sp\lists\types.d.ts(136,86): error TS1005: '(' expected.
[17:28:16] Error - typescript - node_modules\@pnp\sp\sites\types.d.ts(80,27): error TS1110: Type expected.
[17:28:16] Error - typescript - node_modules\@pnp\sp\sites\types.d.ts(80,86): error TS1005: '(' expected.
[17:28:16] Error - typescript - node_modules\@pnp\sp\webs\types.d.ts(20,27): error TS1110: Type expected.
```

![image](https://user-images.githubusercontent.com/7620955/71563632-e37bf480-2a60-11ea-8b37-74bf1e4a3865.png)

I've been looking at this [issue](https://github.com/SharePoint/PnP-JS-Core/issues/741) and I'm also running fully using TS 2.4.2

![image](https://user-images.githubusercontent.com/7620955/71563645-2f2e9e00-2a61-11ea-9905-e24a887417e3.png)

Any magic trick? Thanks!

**Comment by gautamdsheth** [comment]
I guess if you are targeting OnPrem, you need to stick to `TS 2.2.2`. Might need to modify `package-lock.json` file as mentioned [here](https://pnp.github.io/pnpjs/v1/documentation/SPFx-On-Premesis-2016/). 

Also might be a good idea to test and import the setup as below instead of the older way of importing that we used `import {sp} from "@pnp/sp"`:

```Typescript
import { sp } from "@pnp/sp/presets/all";

// ...

protected async onInit(): Promise<void> {

  await super.onInit();

  // other init code may be present

  sp.setup(this.context);
}

// ...

```

**Comment by KEMiCZA** [comment]
I actually had the same issue now that I think about it. I just passed the context as any and it worked. But you're right, this should probably be fixed.

```typescript
  protected onInit(): Promise<void> {

    return super.onInit().then(_ => {
      // @ts-ignore
      sp.setup({
        spfxContext: this.context as any
      });
    });
  }
```

**Comment by KEMiCZA** [comment]
I also have a SP2019 project targetting PnPjs v1.3.1 and I documented these steps to make it compatible with Typescript (similar to https://pnp.github.io/pnpjs/v1/documentation/SPFx-On-Premesis-2016/)

```bash
npm i
npm i -g rimraf # used to remove the node_modules folder (much better/faster)
```
0. Remove the package-lock.json file & node_modules `rimraf node_modules` folder and execute `npm install`
1. Open package-lock.json
2. Search for `"typescript": "2.2.2"` or similair with version 2.2.2
3. Replace "2.2.2" with "2.4.2"
4. Search for the next "typescript" occurance and replace the block with:
```JSON
"typescript": {
  "version": "2.4.2",
  "resolved": "https://registry.npmjs.org/typescript/-/typescript-2.4.2.tgz",
  "integrity": "sha1-+DlfhdRZJ2BnyYiqQYN6j4KHCEQ=",
  "dev": true
}
```
5. Remove node_modules folder `rimraf node_modules`
6. Run `npm install`

**Comment by patrick-rodgers** [comment]
Reading through here want to ensure I am understanding what is happening:

1. There are TS build errors which are fixed via the existing article and the steps outlined [above](https://github.com/pnp/pnpjs/issues/978#issuecomment-569591128) by @KEMiCZA. This is resolved, yes?
2. The `aadTokenProviderFactory` property on our ISPFXContext interface is now required which is messing up SPFx versions that didn't have that property. This has a workaround but is annoying so we should make that optional, yes?

Thanks!

**Comment by sebastienlevert** [comment]
The steps highlighted are good for previous versions of SPFx, but for 1.4.1, it already targets 2.4.2 for TS. This means I still get the same errors at build time, for now. You can reproduce with a simple hello world project including both projects.

For the `aadTokenProviderFactory` I'd be OK with the "as any" as highlighted, but it feels a lot like a hack... Something that would not involve a hack and make the integration with 1.4.1 seamless seems like the best thing!

**Comment by sebastienlevert** [comment]
Sorry for the closing the issue 🤓 Did not mean to do that!

**Comment by tugayevci** [comment]
![pnp_ts_issue](https://user-images.githubusercontent.com/46964249/71655778-9e4e1000-2d49-11ea-95cf-a09ceaf15080.PNG)

 import { sp } from "@pnp/sp/presets/all"; 

Same issue with, Sp2019 and Online with pnp 2.0.

Can't compile it because above errors.  All typescript versions are 2.4.2 in package-lock.json

**Comment by KEMiCZA** [comment]
Okay, so the reason it worked for me previously was because I was targetting PnPjs version 1, which has an older typescript dependency. V2 targets typescript 3.6.4. 

```bash
npm i
npm i -g rimraf # used to remove the node_modules folder (much better/faster)
```
0. Remove the package-lock.json file & node_modules `rimraf node_modules` folder and execute `npm install`
1. Open package-lock.json
2. Search for `"typescript": "2.2.2"` or similair with version 2.2.2
3. Replace "2.2.2" with "3.6.4"
4. Search for the next "typescript" occurance and replace the block with:
```JSON
    "typescript": {
      "version": "3.6.4",
      "resolved": "https://registry.npmjs.org/typescript/-/typescript-3.6.4.tgz",
      "integrity": "sha512-unoCll1+l+YK4i4F8f22TaNVPRHcD9PA3yCuZ8g5e0qGqlVlJ/8FSateOLLSagn+Yg5+ZwuPkL8LFUc0Jcvksg==",
      "dev": true
    },
```
5. Remove node_modules folder `rimraf node_modules`
6. Run `npm install`

If this works, then we should also update the documentation for V2 to reflect this change.

**Comment by tugayevci** [comment]
> Okay, so the reason it worked for me previously was because I was targetting PnPjs version 1, which has an older typescript dependency. V2 targets typescript 3.6.4.
> 
> ```shell
> npm i
> npm i -g rimraf # used to remove the node_modules folder (much better/faster)
> ```
> 
> 1. Remove the package-lock.json file & node_modules `rimraf node_modules` folder and execute `npm install`
> 2. Open package-lock.json
> 3. Search for `"typescript": "2.4.1"` or similair with version 2.4.1
> 4. Replace "2.4.1" with "3.6.4"
> 5. Search for the next "typescript" occurance and replace the block with:
> 
> ```json
>     "typescript": {
>       "version": "3.6.4",
>       "resolved": "https://registry.npmjs.org/typescript/-/typescript-3.6.4.tgz",
>       "integrity": "sha512-unoCll1+l+YK4i4F8f22TaNVPRHcD9PA3yCuZ8g5e0qGqlVlJ/8FSateOLLSagn+Yg5+ZwuPkL8LFUc0Jcvksg==",
>       "dev": true
>     },
> ```
> 
> 1. Remove node_modules folder `rimraf node_modules`
> 2. Run `npm install`
> 
> If this works, then we should also update the documentation for V2 to reflect this change.
> 
> **UPDATE:**
> 
> Compilation/transpiling works but when I try it in a workbench I get the following error:
> 
> ```
> HelloPnPjs.tsx:15 Uncaught (in promise) TypeError: Cannot read property 'get' of undefined
>     at HelloPnPjs.<anonymous> (HelloPnPjs.tsx:15)
>     at step (hello-pn-pjs-web-part.js:2778)
>     at Object.next (hello-pn-pjs-web-part.js:2759)
>     at hello-pn-pjs-web-part.js:2753
>     at new Promise (<anonymous>)
>     at __awaiter (hello-pn-pjs-web-part.js:2749)
>     at HelloPnPjs.test (HelloPnPjs.tsx:14)
>     at new HelloPnPjs (HelloPnPjs.tsx:11)
>     at window.spModuleLoader.p._constructComponentWithoutOwner (sp-webpart-workbench-assembly.js?uniqueId=TSm8d:214)
>     at window.spModuleLoader.p._constructComponent (sp-webpart-workbench-assembly.js?uniqueId=TSm8d:214)
> ```
> 
> code
> 
> ```ts
> import { sp } from '@pnp/sp';
> import { Webs } from '@pnp/sp/webs';
> 
> await sp.web.get();
> ```
> 
> UPDATE 2:
> Works fine now because my import was wrong:
> 
> ```ts
> import { sp } from '@pnp/sp';
> import "@pnp/sp/webs";
> await sp.web.get();
> ```

Works like a charm! Thank you.

**Comment by sebastienlevert** [comment]
This also seems to be working now! I'm not 100% sure if this actually runs OK on SP2019 because of my lack of testing environment, but the workaround provided makes my solution work! Just saw your PR for #990 that would fix the sp.setup, which makes this even better! Great work guys!

**Comment by theibrahimi** [comment]
Hello @KEMiCZA  I've followed all steps as shown above and replace all typescript version in "package-lock.json" with "3.6.4" .
Now I have this errors when i build project :
`Error - typescript - src/webparts/btb/BtbWebPart.ts(25,8): error TS2769: No overload matches this call.
Error - 'typescript' sub task errored after 8.52 s
 TypeScript error(s) occurred.`

when I run `npm list typescript`  I get this output:
![5](https://user-images.githubusercontent.com/7073903/71701022-51108380-2dc7-11ea-8da1-8db260699f95.PNG)

Any suggestions ?

**Comment by KEMiCZA** [comment]
@theibrahimi what's the content of your package.json file? I will try the same on my machine.

**Comment by theibrahimi** [comment]
@KEMiCZA  here's the content of my package.json:

> {
  "name": "myapp",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/loader-set-webpack-public-path": "^3.3.15",
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/sp-http": "^1.9.1",
    "@microsoft/sp-lodash-subset": "~1.4.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0",
    "@microsoft/sp-webpart-base": "~1.4.0",
    "@pnp/common": "^2.0.0",
    "@pnp/graph": "^2.0.0",
    "@pnp/logging": "^2.0.0",
    "@pnp/odata": "^2.0.0",
    "@pnp/pnpjs": "^2.0.0",
    "@pnp/sp": "^2.0.0",
    "@types/es6-promise": "0.0.33",
    "@types/jquery": "^3.3.31",
    "@types/react": "15.6.6",
    "@types/react-dom": "15.5.6",
    "@types/webpack-env": "1.13.1",
    "jquery": "^3.4.1",
    "moment": "^2.24.0",
    "react": "15.6.2",
    "react-dom": "15.6.2",
    "react-moment": "^0.9.7",
    "react-router-dom": "^5.1.2",
    "sp-pnp-node": "^2.2.0",
    "typescript": "^3.6.4"
  },
  "resolutions": {
    "@types/react": "15.6.6"
  },
  "devDependencies": {
    "@microsoft/set-webpack-public-path-plugin": "^2.2.15",
    "@microsoft/sp-build-web": "~1.4.1",
    "@microsoft/sp-module-interfaces": "~1.4.1",
    "@microsoft/sp-webpart-workbench": "~1.4.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "tslint-microsoft-contrib": "^6.2.0"
  }
}

**Comment by patrick-rodgers** [comment]
For v2 you should only need "@pnp/sp": "^2.0.0", as a dep.

**Comment by theibrahimi** [comment]
> For v2 you should only need "@pnp/sp": "^2.0.0", as a dep.

I agree with you and I've uninstall all other dependecies my new "package.json" :

> {
  "name": "btb",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/loader-set-webpack-public-path": "^3.3.15",
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/sp-http": "^1.9.1",
    "@microsoft/sp-lodash-subset": "~1.4.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0",
    "@microsoft/sp-webpart-base": "~1.4.0",
    "@pnp/sp": "^2.0.0",
    "@types/es6-promise": "0.0.33",
    "@types/jquery": "^3.3.31",
    "@types/react": "15.6.6",
    "@types/react-dom": "15.5.6",
    "@types/webpack-env": "1.13.1",
    "jquery": "^3.4.1",
    "moment": "^2.24.0",
    "react": "15.6.2",
    "react-dom": "15.6.2",
    "react-moment": "^0.9.7",
    "react-router-dom": "^5.1.2",
    "typescript": "^3.6.4"
  },
  "resolutions": {
    "@types/react": "15.6.6"
  },
  "devDependencies": {
    "@microsoft/set-webpack-public-path-plugin": "^2.2.15",
    "@microsoft/sp-build-web": "~1.4.1",
    "@microsoft/sp-module-interfaces": "~1.4.1",
    "@microsoft/sp-webpart-workbench": "~1.4.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "tslint-microsoft-contrib": "^6.2.0"
  }
}

Still Have the problem when I run "npm install" or "npm ci" in my package-lock.json I have "@microsoft/gulp-core-build-typescript" wich required  "typescript": "~2.4.1"  if I changed to "3.6.4" the first problem disapear when I build the project but I have the problem discribed in this post

> Hello @KEMiCZA I've followed all steps as shown above and replace all typescript version in "package-lock.json" with "3.6.4" .
> Now I have this errors when i build project :
> `Error - typescript - src/webparts/btb/BtbWebPart.ts(25,8): error TS2769: No overload matches this call. Error - 'typescript' sub task errored after 8.52 s TypeScript error(s) occurred.`
> 
> when I run `npm list typescript` I get this output:
> ![5](https://user-images.githubusercontent.com/7073903/71701022-51108380-2dc7-11ea-8da1-8db260699f95.PNG)
> 
> Any suggestions ?

**Comment by stact** [comment]
I don't know if it's a best practice but I've made this change on package.json:

```
"resolutions": {
    "@types/react": "15.6.6",
    "graceful-fs": "4.2.3",
    "typescript": "3.6.4"
  },
```

**Comment by Gennady-G** [comment]
My solution is targeted to '2019 and Online'.
I try to repeat Your steps, but "typescript" changes back to 

> ~2.4..1
and I get 

>     | `-- typescript@3.6.4  invalid

I installed pnp like this:

> npm install @pnp/logging @pnp/common @pnp/odata @pnp/sp --save

Also added these strings to tsconfig.json (I try use old JSOM code and PnP)

>       "microsoft-ajax",
>       "sharepoint"

package-lock.json:
https://gist.github.com/Gennady-G/2eee8a39a64167f73d42f3f43ab0ac68

package.json:
https://gist.github.com/Gennady-G/d9d0d0fd049f6649bd7e8e1f2c05f66a

tsconfig.json:
https://gist.github.com/Gennady-G/7a5c06079913e5708b91cfa6a6ec6d8c

**Comment by Gennady-G** [comment]
This issue is not resolved for 28 April 2020.
Still no solution. I can provide more details if needed.

**Comment by juliemturner** [comment]
Just noticed this, we do not normally pay attention to submissions on closed issues. If you have a question please submit a new issue completely filling out the issue template. Thanks.

**Comment by Gennady-G** [comment]
Good. I'll reproduce and add new later.

You get errors if
1) make webpart targeted to 2019+Online, 
2) install pnp:
> npm install @pnp/logging @pnp/common @pnp/odata @pnp/sp --save
3) write in Your code 
`import { sp } from "@pnp/sp/presets/all";`
4) gulp bundle

Now I was able to resolve installing old versions, 

> npm install @pnp/sp@1.3.8 @pnp/odata@1.3.8 @pnp/logging@1.3.8 @pnp/common@1.3.8 

Special thanks to @patrick-rodgers https://github.com/pnp/pnpjs/issues/983#issuecomment-569959137
